"""News Clipper 색상 테마 정의"""

# ── 메인 컬러 ──
NAVY = "#1E3A5F"
NAVY_LIGHT = "#264A73"
NAVY_DARK = "#152E4D"
COBALT = "#1A56DB"
COBALT_HOVER = "#1648B8"
SKY_BLUE = "#E1EFFE"

# ── 배경 ──
BG_MAIN = "#F3F6FC"
BG_WHITE = "#FFFFFF"
BG_CARD = "#FFFFFF"

# ── 텍스트 ──
TEXT_PRIMARY = "#1F2937"
TEXT_SECONDARY = "#6B7280"
TEXT_ON_NAVY = "#FFFFFF"
TEXT_ON_NAVY_DIM = "#94A3B8"
TEXT_PLACEHOLDER = "#9CA3AF"

# ── 강조 ──
ACCENT_ORANGE = "#F97316"
SUCCESS = "#10B981"
ERROR = "#EF4444"
WARNING = "#F59E0B"

# ── 티어 뱃지 ──
TIER_1_BG = "#1A56DB"
TIER_1_FG = "#FFFFFF"
TIER_2_BG = "#6B7280"
TIER_2_FG = "#FFFFFF"
TIER_3_BG = "#D1D5DB"
TIER_3_FG = "#374151"

# ── 폰트 ──
FONT_FAMILY = "맑은 고딕"
FONT_TITLE = (FONT_FAMILY, 22, "bold")      
FONT_SUBTITLE = (FONT_FAMILY, 18, "bold")   
FONT_BODY = (FONT_FAMILY, 16)               
FONT_BODY_BOLD = (FONT_FAMILY, 16, "bold")  
FONT_SMALL = (FONT_FAMILY, 14)
FONT_SMALL_BOLD = (FONT_FAMILY, 14, "bold")
FONT_CAPTION = (FONT_FAMILY, 13)
